meta:
  engine: 4.1.0
units:
  kx: cx
  ky: cy
  px: 0.65kx
  py: 0.65ky
  $default_width: cx
  $default_height: cy
points:
  zones:
    matrix:
      anchor:
        shift: [150, -150]
      key:
        padding: 1ky
        spread: 1kx
      columns:
        outer:
          key:
            splay: 12
        pinky:
          key:
            stagger: 0.0ky
            splay: 0
        ring:
          key:
            stagger: 0.8ky
            spread: 1.2kx
            splay: -8
        middle:
          key:
            stagger: 0.2ky
            spread: 1.2kx
            splay: -4
        index:
          key:
            stagger: -0.2ky
            spread: 1.2kx
            splay: -4
        inner:
          key:
            stagger: -0.0ky
            splay: 0
      rows:
        bottom:
        home:
        top:
    thumbtop:
      key:
        padding: 1.1ky
        spread: 1.12kx
      anchor:
        ref: matrix_middle_bottom
        shift: [0.0kx, -1.5ky]
      columns: 
        outer:
          key:
        middle:
          key:
            stagger: -0.1ky
            splay: -10
        home:
          key:
            stagger: -0.1ky
            splay: -10
        inner:
          key:
            stagger: -0.1ky
            splay: -10
    thumbbot:
      key:
        padding: 1.1ky
        spread: 1.12kx
      anchor:
        ref: thumbtop_outer
        shift: [0.8kx, -1.2ky]
      columns:
        outer:
          key:
            splay: -10
        inner:
          key:
            stagger: -0.1ky
            splay: -10
          
outlines:
  keys:
    - what: rectangle
      where: true
      size: [kx-0.01, ky-0.01]
  board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_top
          shift: [-px, py]
        - ref: matrix_ring_top
          shift: [-px, py]
        - ref: matrix_middle_top
          shift: [-px, py]
        - ref: matrix_middle_top
          shift: [px, py]
        - ref: matrix_index_top
          shift: [px, py]
        - ref: matrix_inner_top
          shift: [2.0kx, py]
        - ref: matrix_inner_top
          shift: [2.0kx, -3.0ky]
        - ref: thumbtop_inner
          shift: [px, py]
        - ref: thumbtop_inner
          shift: [px, -py]
        - ref: thumbbot_inner
          shift: [px, -py]
        - ref: thumbbot_outer
          shift: [-px, -py]
        - ref: thumbtop_outer
          shift: [-px, -py]
        - ref: matrix_pinky_bottom
          shift: [px, -py]
        - ref: matrix_outer_bottom
          shift: [-px, -py]
      fillet: 5
  combo:
    - name: board
    - operation: subtract
      name: keys
pcbs:
  board:
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode_sod123
        where: true
        params:
          reversible: true
          include_traces_vias: true
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift:
            [0, -5]
      micro:
        what: nicenano
        params:
          reversible: true
          reverse_mount: true
          include_traces: true
        where:
          ref: matrix_inner_top
          shift: [1.2kx, -0.5ky]
          rotate: 0
      display:
        what: niceview
        params:
          reversible: true
          include_traces: true
        where:
          ref: matrix_inner_top
          shift: [1.2kx, -0.7ky]
          rotate: 0
cases:
